### ISSUE TITLE
Can not run Streamr Client in M1

### ISSUE THREAD

**Issue by thanhlmm** [streamr-dev/network#279]
I can not install Streamr client on my M1 laptop, I think the problem with node-sqlite3 

```
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-darwin-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.0 | darwin | arm64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:441:11)
gyp ERR! stack     at Socket.emit (events.js:376:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:673:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/thanhminh/.nvm/versions/node/v14.17.0/bin/node" "/Users/thanhminh/github/streamr-chart/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/thanhminh/github/streamr-chart/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/thanhminh/github/streamr-chart/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3" "--python=/usr/local/bin/python"
gyp ERR! cwd /Users/thanhminh/github/streamr-chart/node_modules/sqlite3
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/thanhminh/.nvm/versions/node/v14.17.0/bin/node /Users/thanhminh/github/streamr-chart/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/thanhminh/github/streamr-chart/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/thanhminh/github/streamr-chart/node_modules/sqlite3/lib/binding/napi-v3-darwin-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=/usr/local/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/thanhminh/github/streamr-chart/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/Users/thanhminh/.nvm/versions/node/v14.17.0/bin/node" "/Users/thanhminh/github/streamr-chart/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/thanhminh/github/streamr-chart/node_modules/sqlite3
node-pre-gyp ERR! node -v v14.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/thanhminh/.nvm/versions/node/v14.17.0/bin/node /Users/thanhminh/github/streamr-chart/node_modules/node-gyp/bin/node-gyp.js con
```

**Comment by thanhlmm** [comment]
It might be related to this: https://github.com/mapbox/node-sqlite3/issues/1516

The temporary solution is use `npm` instead of `yarn`

**Comment by fonty1** [comment]
Thanks @thanhlmm I wasn't aware of this as we use NPM internally. I'll make a note about this in the readme.
